// Mocks generated by Mockito 5.4.4 from annotations
// in investment_tracking/test/features/property_tracking/presentation/manager/property_list_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:investment_tracking/features/property_tracking/domain/entities/rental_event.dart'
    as _i5;
import 'package:investment_tracking/features/property_tracking/domain/repositories/property_repository.dart'
    as _i2;
import 'package:investment_tracking/features/property_tracking/domain/usecases/get_current_month_rental_events.dart'
    as _i3;
import 'package:investment_tracking/features/property_tracking/domain/usecases/mark_event_as_paid.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePropertyRepository_0 extends _i1.SmartFake
    implements _i2.PropertyRepository {
  _FakePropertyRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCurrentMonthRentalEvents].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentMonthRentalEvents extends _i1.Mock
    implements _i3.GetCurrentMonthRentalEvents {
  MockGetCurrentMonthRentalEvents() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PropertyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePropertyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PropertyRepository);

  @override
  _i4.Future<List<_i5.RentalEvent>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.RentalEvent>>.value(<_i5.RentalEvent>[]),
      ) as _i4.Future<List<_i5.RentalEvent>>);
}

/// A class which mocks [MarkEventAsPaid].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkEventAsPaid extends _i1.Mock implements _i6.MarkEventAsPaid {
  MockMarkEventAsPaid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PropertyRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePropertyRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PropertyRepository);

  @override
  _i4.Future<void> call(_i5.RentalEvent? event) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
