// Mocks generated by Mockito 5.4.4 from annotations
// in investment_tracking/test/features/property_tracking/presentation/pages/property_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:investment_tracking/features/property_tracking/domain/usecases/mark_event_as_paid.dart'
    as _i2;
import 'package:investment_tracking/features/property_tracking/presentation/manager/property_list_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMarkEventAsPaid_0 extends _i1.SmartFake
    implements _i2.MarkEventAsPaid {
  _FakeMarkEventAsPaid_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PropertyListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropertyListNotifier extends _i1.Mock
    implements _i3.PropertyListNotifier {
  MockPropertyListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MarkEventAsPaid get markEventAsPaidUseCase => (super.noSuchMethod(
        Invocation.getter(#markEventAsPaidUseCase),
        returnValue: _FakeMarkEventAsPaid_0(
          this,
          Invocation.getter(#markEventAsPaidUseCase),
        ),
      ) as _i2.MarkEventAsPaid);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<dynamic> get properties => (super.noSuchMethod(
        Invocation.getter(#properties),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> fetchProperties() => (super.noSuchMethod(
        Invocation.method(
          #fetchProperties,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markPropertyAsPaid(String? propertyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPropertyAsPaid,
          [propertyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
